"""CLI module - provides chaosblade-exec-python command with subcommands.

Commands:
  start   - Start the agent (standalone or attach to running process)
  stop    - Stop the agent
  status  - Show agent status
  attach  - Generate sitecustomize.py for auto-attach on process start
  detach  - Remove the sitecustomize.py hook
  spec    - Export plugin spec YAML for chaosblade CLI
"""

from __future__ import annotations

import argparse
import json
import os
import sys
import textwrap
from pathlib import Path
from typing import Any
from urllib.request import urlopen, Request
from urllib.error import URLError


# Default configuration
DEFAULT_HOST = "127.0.0.1"
DEFAULT_PORT = 9526
SITECUSTOMIZE_MARKER = "# CHAOSBLADE_AGENT_HOOK"


def _get_agent_url(host: str, port: int) -> str:
    return f"http://{host}:{port}"


def _http_get(url: str, timeout: float = 5.0) -> dict[str, Any] | None:
    """Make a simple HTTP GET request and return JSON response."""
    try:
        req = Request(url)
        with urlopen(req, timeout=timeout) as resp:
            return json.loads(resp.read().decode())
    except (URLError, OSError, json.JSONDecodeError, TimeoutError):
        return None


def cmd_start(args: argparse.Namespace) -> int:
    """Start the ChaosBlade agent."""
    import logging
    from chaosblade.bootstrap.agent import ChaosBladeAgent

    level = logging.DEBUG if args.debug else logging.INFO
    logging.basicConfig(
        level=level,
        format="%(asctime)s [%(levelname)s] %(name)s: %(message)s",
    )

    agent = ChaosBladeAgent(port=args.port, host=args.host)
    agent.start()

    print(f"ChaosBlade Python Agent started on {args.host}:{args.port}")
    print(f"  Plugins loaded: {agent.patcher.get_patch_count()} patches active")
    print(f"  Management API: {_get_agent_url(args.host, args.port)}")
    print("Press Ctrl+C to stop...")

    try:
        import threading
        threading.Event().wait()
    except KeyboardInterrupt:
        print("\nShutting down...")
        agent.stop()

    return 0


def cmd_status(args: argparse.Namespace) -> int:
    """Query agent status via /health endpoint."""
    url = f"{_get_agent_url(args.host, args.port)}/health"
    resp = _http_get(url)

    if resp is None:
        print(f"Agent not reachable at {args.host}:{args.port}")
        return 1

    print("Agent Status: RUNNING")
    print(f"  Address: {args.host}:{args.port}")
    if "result" in resp:
        result = resp["result"]
        if isinstance(result, dict):
            for k, v in result.items():
                print(f"  {k}: {v}")
        else:
            print(f"  Result: {result}")

    # Also try to list active experiments
    list_url = f"{_get_agent_url(args.host, args.port)}/list"
    list_resp = _http_get(list_url)
    if list_resp and list_resp.get("success") and "result" in list_resp:
        experiments = list_resp["result"]
        if isinstance(experiments, list) and experiments:
            print(f"\n  Active Experiments ({len(experiments)}):")
            for exp in experiments:
                if isinstance(exp, dict):
                    print(f"    - [{exp.get('uid', '?')}] {exp.get('target', '?')}:{exp.get('action', '?')}")
        elif isinstance(experiments, list):
            print("\n  Active Experiments: (none)")
    return 0


def cmd_attach(args: argparse.Namespace) -> int:
    """Generate sitecustomize.py to auto-start agent on Python process startup.

    This enables the agent to be injected into any Python process by setting
    PYTHONPATH to include the directory containing sitecustomize.py.
    """
    target_dir = Path(args.target_dir).resolve()
    target_dir.mkdir(parents=True, exist_ok=True)

    sitecustomize_path = target_dir / "sitecustomize.py"

    content = textwrap.dedent(f"""\
        {SITECUSTOMIZE_MARKER}
        # Auto-generated by chaosblade-exec-python attach
        # This file starts the ChaosBlade agent when the Python process starts.
        import os as _os

        def _start_chaosblade_agent():
            try:
                from chaosblade.bootstrap.agent import ChaosBladeAgent
                import logging
                logging.basicConfig(
                    level=logging.INFO,
                    format="%(asctime)s [%(levelname)s] %(name)s: %(message)s",
                )
                _host = _os.environ.get("CHAOSBLADE_HOST", "{args.host}")
                _port = int(_os.environ.get("CHAOSBLADE_PORT", "{args.port}"))
                agent = ChaosBladeAgent(port=_port, host=_host)
                agent.start()
            except Exception as e:
                import sys
                print(f"[ChaosBlade] Failed to start agent: {{e}}", file=sys.stderr)

        _start_chaosblade_agent()
        del _start_chaosblade_agent
    """)

    # Check for existing sitecustomize.py
    if sitecustomize_path.exists():
        existing = sitecustomize_path.read_text()
        if SITECUSTOMIZE_MARKER in existing:
            print(f"Already attached at: {sitecustomize_path}")
            return 0
        else:
            # Append to existing sitecustomize.py
            with open(sitecustomize_path, "a") as f:
                f.write("\n\n")
                f.write(content)
            print(f"Appended agent hook to existing: {sitecustomize_path}")
    else:
        sitecustomize_path.write_text(content)
        print(f"Created: {sitecustomize_path}")

    print(f"\nTo activate, set PYTHONPATH:")
    print(f"  export PYTHONPATH=\"{target_dir}:$PYTHONPATH\"")
    print(f"\nOr use environment variables to configure:")
    print(f"  CHAOSBLADE_HOST={args.host}")
    print(f"  CHAOSBLADE_PORT={args.port}")
    return 0


def cmd_detach(args: argparse.Namespace) -> int:
    """Remove the sitecustomize.py hook."""
    target_dir = Path(args.target_dir).resolve()
    sitecustomize_path = target_dir / "sitecustomize.py"

    if not sitecustomize_path.exists():
        print(f"No sitecustomize.py found at: {target_dir}")
        return 1

    content = sitecustomize_path.read_text()
    if SITECUSTOMIZE_MARKER not in content:
        print(f"No ChaosBlade hook found in: {sitecustomize_path}")
        return 1

    # If the entire file is our hook, remove it
    lines = content.split("\n")
    # Find the marker and remove everything from it until end or next non-chaosblade section
    new_lines = []
    skip = False
    for line in lines:
        if SITECUSTOMIZE_MARKER in line:
            skip = True
            continue
        if skip:
            # Skip until we find a line that's not indented and not empty
            # and doesn't look like our generated code
            if line.startswith("del _start_chaosblade_agent"):
                skip = False
                continue
            continue
        new_lines.append(line)

    remaining = "\n".join(new_lines).strip()
    if remaining:
        sitecustomize_path.write_text(remaining + "\n")
        print(f"Removed ChaosBlade hook from: {sitecustomize_path}")
    else:
        sitecustomize_path.unlink()
        print(f"Removed: {sitecustomize_path}")

    return 0


def cmd_spec(args: argparse.Namespace) -> int:
    """Export chaosblade-python-spec-<version>.yaml."""
    from chaosblade import __version__
    from chaosblade.bootstrap.plugin_loader import PluginLoader
    from chaosblade.common.center.manager_factory import ManagerFactory

    PluginLoader.load_plugins()

    manager = ManagerFactory.get_model_spec_manager()
    items: list[dict[str, Any]] = []

    for model_spec in manager.list_all():
        # Compute matchers once per model (same for all actions)
        matchers = [
            {
                "name": m.get_name(),
                "desc": m.get_desc(),
                "noArgs": m.no_args(),
                "required": m.is_required(),
            }
            for m in model_spec.get_matcher_specs()
        ]

        actions: list[dict[str, Any]] = []
        for action in model_spec.get_actions():
            action_flags = [
                {
                    "name": f.get_name(),
                    "desc": f.get_desc(),
                    "noArgs": f.no_args(),
                    "required": f.is_required(),
                }
                for f in action.get_action_flags()
            ]
            action_entry: dict[str, Any] = {
                "action": action.get_name(),
                "shortDesc": action.get_short_desc(),
                "longDesc": action.get_long_desc(),
            }
            aliases = action.get_aliases()
            if aliases:
                action_entry["aliases"] = aliases
            if matchers:
                action_entry["matchers"] = matchers
            if action_flags:
                action_entry["flags"] = action_flags
            actions.append(action_entry)

        items.append({
            "target": model_spec.get_target(),
            "shortDesc": model_spec.get_short_desc(),
            "longDesc": model_spec.get_long_desc(),
            "scope": "host",
            "actions": actions,
        })

    payload = {
        "version": "v1",
        "kind": "plugin",
        "items": items,
    }

    output_file = args.output or f"chaosblade-python-spec-{__version__}.yaml"
    # Use JSON (valid YAML subset) to avoid PyYAML dependency
    Path(output_file).write_text(json.dumps(payload, ensure_ascii=False, indent=2))
    print(f"Exported spec to: {output_file}")
    return 0


def main() -> int:
    """Main CLI entry point."""
    parser = argparse.ArgumentParser(
        prog="chaosblade-exec-python",
        description="ChaosBlade Python Agent - Chaos engineering for Python applications",
    )
    parser.add_argument(
        "--version", action="version", version="%(prog)s 0.1.0"
    )

    subparsers = parser.add_subparsers(dest="command", help="Available commands")

    # start command
    start_parser = subparsers.add_parser("start", help="Start the agent")
    start_parser.add_argument("--port", type=int, default=DEFAULT_PORT, help="HTTP server port")
    start_parser.add_argument("--host", type=str, default=DEFAULT_HOST, help="HTTP server host")
    start_parser.add_argument("--debug", action="store_true", help="Enable debug logging")

    # status command
    status_parser = subparsers.add_parser("status", help="Query agent status")
    status_parser.add_argument("--port", type=int, default=DEFAULT_PORT)
    status_parser.add_argument("--host", type=str, default=DEFAULT_HOST)

    # attach command
    attach_parser = subparsers.add_parser("attach", help="Generate sitecustomize.py hook")
    attach_parser.add_argument(
        "--target-dir", type=str, default=".",
        help="Directory to place sitecustomize.py (default: current directory)"
    )
    attach_parser.add_argument("--port", type=int, default=DEFAULT_PORT)
    attach_parser.add_argument("--host", type=str, default=DEFAULT_HOST)

    # detach command
    detach_parser = subparsers.add_parser("detach", help="Remove sitecustomize.py hook")
    detach_parser.add_argument(
        "--target-dir", type=str, default=".",
        help="Directory containing sitecustomize.py"
    )

    # spec command
    spec_parser = subparsers.add_parser("spec", help="Export plugin spec YAML")
    spec_parser.add_argument(
        "--output", type=str, default=None,
        help="Output file path (default: chaosblade-python-spec-<version>.yaml)"
    )

    args = parser.parse_args()

    if args.command is None:
        parser.print_help()
        return 0

    commands = {
        "start": cmd_start,
        "status": cmd_status,
        "attach": cmd_attach,
        "detach": cmd_detach,
        "spec": cmd_spec,
    }

    handler = commands.get(args.command)
    if handler:
        return handler(args)
    else:
        parser.print_help()
        return 1


def cli_entry() -> None:
    """Entry point for the console_scripts."""
    sys.exit(main())
